name: example
description: Dashbook example

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0" # dart version
  flutter: ">=3.3.0"

dependencies:
  alkami_core_dependencies:
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^4.0.0

  dashbook:
    path: ../

  flutter:
    sdk: flutter

dev_dependencies:

flutter:
  uses-material-design: true
