name: example
description: Dashbook example

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0" # dart version
  flutter: ">=3.3.0"

dependencies:
  dashbook:
    path: ../

  flutter:
    sdk: flutter

  flutter_platform:
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^1.0.0

dev_dependencies:

flutter:
  uses-material-design: true
